ktor:
  application:
    modules:
      - com.helltar.homepage.ApplicationKt.module
  deployment:
    port: 8443
    workerGroupSize: 4
    callGroupSize: 16
    connectionGroupSize: 8

homepage:
  apikey: $API_KEY

github:
  token: $GITHUB_TOKEN
